version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: support_registry
      - name: player_game_ingest

  - name: silver
    schema: silver
    tables:
      - name: support_registry
      - name: player_game
      - name: team_game

  - name: gold
    schema: gold
    tables:
      - name: match_scoreboard